 
PROPOSITION = "Satz"
CONJECTURE = "Vermutung"
THEOREM = "Hauptsatz"
LEMMA = "Hilfsatz"
COROLLARY = "Folgerung"
OBSERVATION = "Bemerkung"
AFFIRMATION = "Behauptung"
NOTATION = "Bezeichnung"
DEFINITION = "Definition"
EXAMPLE = "Beispiel"
PROOF = "Beweis"
TO_PROOF = "Zum Beweis"
PROOF_OF = "Beweis von"
EQ = "Gl."
